### ISSUE TITLE
Couple of suggestions

### ISSUE THREAD

**Issue by frogmaster** [listofoptions/TH-XWhatsIt#2]
Would have done a pull request, but kicad library management was driving me nuts. 

As model F AT has soldered ribbon cable with 3.96mm pitch, add optional pads, connected 1-to-1 to existing plugboard connector. Positioning is important in horizontal direction as AT case has molded screw mount near there. The distance from the edge of the board to edge of pads shoult no exceed 16mm.  See the attached screenshot.

![Screenshot_20200726_215149](https://user-images.githubusercontent.com/736310/88487183-8b23bb80-cf8b-11ea-9bbe-96aff20865bc.png)

Also, the ground strap connector hole is annoyingly small, dealing with 2mm screws and standoffs is just painful. Maybe increase the hole size from 2.2mm to 3.5.

**Comment by listofoptions** [comment]
we've got a branch working on this, and a few other issues that where brought to mind, so the next revision will fix this

**Comment by listofoptions** [comment]
@frogmaster check the repo now, @purdeaandrei has done some major rework instead.

**Comment by frogmaster** [comment]
Better. Although, the tiny mounting hole is still there, i would use 3.5mm hole for mounting with 3mm standoffs, if there's not a particular reason for the tiny one. 

Still, i will probably design a single board specially for model f at with mounting holes in same places as the ibm board, and incorporate the changes made by Andrei into that. The double layer plugboard and elongated design just doesn't fit that particular keyboard very well. I will not do so soon though, as it's gotten a little busy at work.

**Comment by purdeaandrei** [comment]
I believe the latest revision solves all of these problems, so we can close this issue.

By the way @frogmaster , nice work on the Model F-specific adaptation!

Andrei

**Comment by purdeaandrei** [comment]
@frogmaster Closing this issue, please re-open if you think something has not been addressed adequately.
